CREATE DATABASE IF NOT EXISTS gamesup CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
CREATE USER IF NOT EXISTS 'gamesup'@'%' IDENTIFIED BY 'gamesup';
GRANT ALL PRIVILEGES ON gamesup.* TO 'gamesup'@'%';
FLUSH PRIVILEGES;